### ISSUE TITLE
Error shows when initializing the game

### ISSUE THREAD

**Issue by hcho1989** [risc0/battleship-example#16]
on the self hosted web client, after I keyed in my game name and click return, on the grid page, the console shows the following

```
INFO web/client/src/game.rs:190 Game session does not exist, initializing game
near-api-js.js:78 Receipt: 58oXRHbFopLNwKeQTtzbC6CuRJ1596qmBCpU42SkXcCM
```

The tx seemed to have gone through

https://explorer.testnet.near.org/transactions/BdrbQJrCPZvCKye8rWqUC2xPQUHkSgqogZBKxfvoUP8#58oXRHbFopLNwKeQTtzbC6CuRJ1596qmBCpU42SkXcCM

yet an error message shows on the frontend

```
new_game: JsValue(Error: Error happened during instantiation Error: Error happened during instantiation at Object.parseResultError (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:3611:29) at ConnectedWalletAccount.signAndSendTransactionV2 (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:163:36) at async ConnectedWalletAccount._signAndSendTransaction (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:4055:24) at async Contract._changeMethod (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:1076:27))

```

**Comment by hcho1989** [comment]
P.S. I deployed my contracts following the README, and updated web/client/near.js#L16

**Comment by 84matte84** [comment]
> on the self hosted web client, after I keyed in my game name and click return, on the grid page, the console shows the following
> 
> ```
> INFO web/client/src/game.rs:190 Game session does not exist, initializing game
> near-api-js.js:78 Receipt: 58oXRHbFopLNwKeQTtzbC6CuRJ1596qmBCpU42SkXcCM
> ```
> 
> The tx seemed to have failed
> 
> https://explorer.testnet.near.org/transactions/BdrbQJrCPZvCKye8rWqUC2xPQUHkSgqogZBKxfvoUP8#58oXRHbFopLNwKeQTtzbC6CuRJ1596qmBCpU42SkXcCM
> 
> An error message shows on the frontend
> 
> ```
> new_game: JsValue(Error: Error happened during instantiation Error: Error happened during instantiation at Object.parseResultError (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:3611:29) at ConnectedWalletAccount.signAndSendTransactionV2 (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:163:36) at async ConnectedWalletAccount._signAndSendTransaction (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:4055:24) at async Contract._changeMethod (https://cdn.jsdelivr.net/npm/near-api-js@0.41.0/dist/near-api-js.js:1076:27))
> ```

Hi hcho1989, have you found a way to fix it? Cause I am also having same issue.....
